<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-21 13:03:25.630 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div class="comp-date-string">
        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">日期（字面量）选择器</span>
                    <code>b-date-string</code>
                </h2>
                <b-md-view :md-text="MD.CompDateStringOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompDateStringBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompDateStringBasicCode"/></div>
                    <div slot="main">
                        <b-date-string v-model="demo.basic"/>
                    </div>
                    <div slot="output">The output is {{ demo.basic }}</div>
                </demo-box>
            </div>

            <div class="case">
                <h3>一致性</h3>
                <b-md-view :md-text="MD.CompDateStringConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompDateStringAPI"/>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    export default {
        name: 'CompDateString',

        data() {
            return {
                MD,
                demo: {
                    basic: null
                }
            };
        }
    };

</script>
