<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-10-15 13:01:02.916 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>

    <div class="comp-layout">
        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">布局与导航</span>
                    <code>b-layout</code>
                </h2>
                <b-md-view :md-text="MD.CompLayoutOverview"/>
            </div>

            <div class="case">
                <h3>顶部导航布局</h3>
                <b-md-view :md-text="MD.CompLayoutNavTop"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompLayoutNavTopCode"/></div>
                    <div slot="main">
                        <div class="container-viewport">
                            <b-layout>
                                <div slot="header">
                                    <b-nav-top :routes="routes">
                                        <div slot="left">My App</div>
                                        <div slot="right"><i class="b-icon-github"></i></div>
                                    </b-nav-top>
                                </div>

                                <div slot="content">
                                    <div class="center-block top-demo">
                                        main content
                                    </div>
                                </div>
                            </b-layout>
                        </div>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>侧边导航布局</h3>
                <b-md-view :md-text="MD.CompLayoutHeaderNavSide"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompLayoutHeaderNavSideCode"/></div>
                    <div slot="main">
                        <div class="container-viewport">
                            <b-layout
                                :is-nav-open="sideNavIsNavOpen"
                                @nav-open-change="setSideNavOpen">
                                <div slot="header">
                                    <b-header @on-nav-toggle="toggleSideNavOpen">
                                        <div slot="center">
                                            <h4>Page Title</h4>
                                        </div>

                                        <div slot="right">
                                            <i class="b-icon-github"></i>
                                        </div>
                                    </b-header>
                                </div>

                                <div slot="side-left">
                                    <b-nav-side :routes="routes" @toggle="toggleSideNavOpen">
                                        <div slot="nav-top">
                                            My App
                                        </div>
                                    </b-nav-side>
                                </div>

                                <div slot="content">
                                    <div class="center-block">
                                        main content
                                    </div>
                                </div>
                            </b-layout>
                        </div>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompLayoutAPI"/>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    const routes = [
        {
            name: 'Component',
            meta: {
                navTitle: 'Component'
            },
            children: [
                {
                    name: 'CompLayout',
                    meta: {
                        navTitle: 'Layout'
                    }
                },
                {
                    name: 'CompMdEditor',
                    meta: {
                        navTitle: 'Markdown Editor'
                    }
                }
            ]
        }
    ];

    export default {
        name: 'CompLayout',

        data() {
            return {
                MD,
                routes,
                sideNavIsNavOpen: true
            };
        },

        methods: {
            setSideNavOpen(isOpen) {
                this.sideNavIsNavOpen = isOpen;
            },

            toggleSideNavOpen() {
                this.sideNavIsNavOpen = !this.sideNavIsNavOpen;
            }
        }
    };

</script>

<style lang="scss" scoped>
    @import "../../../../../src/style/variables.scss";

    .comp-layout {
        .container-viewport {
            position: relative;
            height: 500px;
            transform: translate(0, 0);
            overflow: auto;

            .center-block {
                display: flex;
                width: 100%;
                height: 452px;
                box-sizing: border-box;
                align-items: center;
                justify-content: center;
                background-color: $gray-lighter;

                &.top-demo {
                    height: 404px;
                }
            }
        }
    }
</style>

