<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-25 11:14:39.720 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div
        :class="className"
        class="b-card"
        @click="handleClick"
        @mouseover="handleMouseOver"
        @mouseout="handleMouseOut"
        @mouseenter="handleMouseEnter"
        @mouseleave="handleMouseLeave">

        <slot></slot>

    </div>

</template>

<script type="text/babel">
    import {isValidSize} from './helper/helper';

    export default {
        name: 'BCard',

        props: {
            clickable: {
                type: Boolean,
                default: false
            },

            name: {
                type: String,
                default: null
            },

            size: {
                type: String,
                validator: isValidSize,
                default: 'md'
            }
        },

        computed: {
            className() {
                const vm = this;
                const {clickable, size} = vm;

                return [
                    `size-${size}`,
                    {clickable}
                ];
            }
        },

        methods: {
            handleClick(event) {
                const vm = this;
                const {clickable} = vm;

                if (clickable) {
                    vm.$emit('click', event);
                }
            },

            handleMouseOver(event) {
                const vm = this;
                const {clickable} = vm;

                if (clickable) {
                    vm.$emit('mouseover', event);
                }
            },

            handleMouseOut(event) {
                const vm = this;
                const {clickable} = vm;

                if (clickable) {
                    vm.$emit('mouseout', event);
                }
            },

            handleMouseEnter(event) {
                const vm = this;
                const {clickable} = vm;

                if (clickable) {
                    vm.$emit('mouseenter', event);
                }
            },

            handleMouseLeave(event) {
                const vm = this;
                const {clickable} = vm;

                if (clickable) {
                    vm.$emit('mouseleave', event);
                }
            }
        }
    };

</script>
