<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-16 17:12:07.835 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <div class="comp-form">
        <h4 class="heading">Form</h4>

        <div class="card">
            <b-form v-model="data" :options="options" class="form-block" @reset="reset">
                <b-form-group slot="custom" label="自定义 field">
                    <b-input v-model="data.custom"/>
                </b-form-group>
            </b-form>
        </div>

        <pre class="json-preview">{{ $j(data) }}</pre>
    </div>

</template>

<script type="text/babel">
    const options = {
        fieldDefs: [
            {label: '名称', field: 'name'},
            {field: 'custom'},
            {type: 'br'},
            {label: '科目', field: 'type', type: 'select', props: {map: {a: 'a', b: 'b'}}},
            {label: '科目层级', field: 'level', type: 'select', props: {
                map: {
                    one: '一级',
                    two: '二级',
                    three: '三级'
                },
                multiple: true
            }},
            {label: '省市', field: 'area', type: 'select-cascader', props: {
                list: [
                    {label: '北京', value: 1, children: [{label: '北京', value: 2}]},
                    {label: '湖北', value: 3, children: [{label: '武汉', value: 4}, {label: '黄冈', value: 5}]},
                    {label: '广东', value: 6, children: [{label: '广州', value: 7}, {label: '深圳', value: 8}]}
                ]
            }},
            {label: '时间', field: 'time', type: 'date'},
            {label: '生日', field: 'timeString', type: 'dateString'}
        ],
        btnDefs: [
            {text: 'Reset', event: 'reset'}
        ]
    };

    export default {
        name: 'CompForm',

        data() {
            return {
                options,

                data: {
                    name: '123',
                    custom: ''
                }
            };
        },

        methods: {
            reset() {
                this.data = {};
            }
        }
    };

</script>
