<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-16 14:57:22.524 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <form class="b-form" @submit.prevent="submit">
        <slot
            v-for="fieldDef in options.fieldDefs"
            :name="fieldDef.field"
            :fieldDef="fieldDef">
            <b-form-group :label="fieldDef.label">
                <component
                    :value="data[fieldDef.field]"
                    :is="is(fieldDef.type)"
                    v-bind="fieldDef.props"
                    @input="emit(arguments, fieldDef)"
                    @change="emit(arguments, fieldDef)"/>
            </b-form-group>
        </slot>
    </form>

</template>

<script type="text/babel">

    import {FieldMap} from './constant/filed';

    export default {
        name: 'BForm',

        model: {
            prop: 'data',
            event: 'change'
        },

        props: {
            data: {
                type: Object,
                required: true
            },

            options: {
                type: Object,
                default: () => {}
            }
        },

        methods: {
            is(type) {
                return FieldMap[type] || FieldMap.text;
            },

            emit(data, {field}) {
                this.$emit('change', {
                    ...this.data,
                    [field]: data[0]
                });
            }
        }
    };

</script>
