<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-16 14:57:22.524 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <form class="b-form" @submit.prevent="emitEvent('submit')">
        <template v-for="(fieldDef, index) in renderFieldDefs">
            <slot
                v-if="fieldDef.field"
                :name="fieldDef.field"
                :fieldDef="fieldDef">
                <b-form-group
                    :label="fieldDef.label"
                    :has-star="fieldDef.hasStar">
                    <component
                        :value="data[fieldDef.field]"
                        :is="is(fieldDef.type)"
                        v-bind="fieldDef.props"
                        @change="emitChange(arguments, fieldDef)"/>
                </b-form-group>
            </slot>

            <br v-else-if="fieldDef.type === 'br'" :key="index">
        </template>

        <template v-if="hasBtns">
            <template v-for="(btnDef, index) in options.btnDefs">
                <button
                    v-if="btnDef.event"
                    :key="btnKey(btnDef)"
                    v-bind="btnDef.props"
                    :type="btnType(btnDef.props)"
                    class="form-button"
                    @click="emitEvent(btnDef.event)">{{ btnDef.text }}</button>

                <br v-else-if="btnDef.type === 'br'" :key="index">
            </template>
        </template>

        <slot name="actions"></slot>

        <button
            v-if="options.mainFieldCount"
            class="link"
            @click="changeFold">
            Collapse <i :class="{'b-icon-collapse-up': !isFold, 'b-icon-collapse-down': isFold}"></i>
        </button>
    </form>

</template>

<script type="text/babel">

    import {FieldMap} from './constant/field';
    import {isNumber} from '../../util/check';

    export default {
        name: 'BForm',

        model: {
            prop: 'data',
            event: 'change'
        },

        props: {
            data: {
                type: Object,
                required: true
            },

            options: {
                type: Object,
                default: () => {}
            }
        },

        data() {
            return {
                isFold: true
            };
        },

        computed: {
            renderFieldDefs() {
                const vm = this;
                const {options: {fieldDefs, mainFieldCount}, isFold} = vm;

                return isFold && isNumber(mainFieldCount)
                    ? fieldDefs.slice(0, mainFieldCount - 1)
                    : fieldDefs;
            },

            hasBtns() {
                const vm = this;

                return vm.options.btnDefs && vm.options.btnDefs.length > 0;
            }
        },

        methods: {
            is(type) {
                return FieldMap[type] || FieldMap.text;
            },

            btnType(props = {}) {
                return props.type || 'button';
            },

            btnKey({text, event}) {
                return text + event;
            },

            emitChange(data, {field, type}) {
                const emitData = {
                    ...this.data,
                    [field]: data[0]
                };

                if (data[0] === null || (!type && data[0] === '')) {
                    delete emitData[field];
                }

                this.$emit('change', emitData, field);
            },

            emitEvent(event) {
                this.$emit(event);
            },

            changeFold() {
                this.isFold = !this.isFold;
            }
        }
    };

</script>
