<!-- @author smwang -->
<!-- @email smwang@yangqianguan.com -->
<!-- @date 2018-11-07 12:17:06.075 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>

    <div class="comp-tag-input">
        <h4 class="heading">TagInput</h4>

        <div class="card">
            <form class="form-block" @submit.prevent>
                <b-form-group label="basic">
                    <b-tag-input v-model="basic"/>
                </b-form-group>
            </form>
        </div>

        <pre class="json-preview">{{ $j(basic) }}</pre>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'CompTagInput',

        data() {
            return {
                basic: ['标签1', '标签2']
            };
        }
    };

</script>
