<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-07-03 15:48:50.770 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="comp-select-cascader">
        <h4 class="heading">Cascader Select</h4>
        <div class="card">
            <form class="form-inline">
                <b-form-group label="Basic">
                    <b-select-cascader
                        v-model="editing.basic"
                        :list="BasicForest"/>
                </b-form-group>

                <b-form-group label="With Default Value">
                    <b-select-cascader
                        v-model="editing.default"
                        :list="BasicForest"/>
                </b-form-group>

                <b-form-group label="Emit List">
                    <b-select-cascader
                        v-model="editing.emitList"
                        :list="BasicForest"
                        :options="EmitListOptions"/>
                </b-form-group>

                <b-form-group label="Emit List With Default Value">
                    <b-select-cascader
                        v-model="editing.emitListWithDefault"
                        :list="BasicForest"
                        :options="EmitListOptions"/>
                </b-form-group>

                <b-form-group label="Disabled">
                    <b-select-cascader
                        v-model="editing.disabled"
                        :disabled="true"
                        :list="BasicForest"/>
                </b-form-group>
            </form>
        </div>

        <pre class="json-preview">{{ $j(editing) }}</pre>
    </div>

</template>

<script type="text/babel">

    import {BasicForest} from './constant/forest';
    import {EmitListOptions} from './constant/options';

    export default {
        name: 'CompSelectCascader',

        data() {
            return {
                BasicForest,
                EmitListOptions,
                editing: {
                    basic: null,
                    default: 3,
                    emitList: null,
                    emitListWithDefault: [1, 2, 3],
                    disabled: 30
                }
            };
        }
    };

</script>

