<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-10-16 15:34:43.151 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>
    <div v-b-hotkey="keyMap" v-if="visible" class="b-image-gallery-modal-wrapper">
        <div class="gallery-tip one">{{ index + 1 }} / {{ imageList.length }}</div>
        <i v-if="canGoPrev" class="go-left b-icon-left one fast" @click.stop="goPrev"></i>
        <i v-if="canGoNext" class="go-right b-icon-right one fast" @click.stop="goNext"></i>

        <b-dialog :open="visible" class="b-image-gallery-modal" @close="cancel">
            <div class="b-image-check-modal-body" @click="cancel">
                <div class="image-preview">
                    <img v-if="!isSwitching" :src="currentImage.uri">
                </div>
            </div>
        </b-dialog>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BImageGalleryModal',

        props: {
            imageList: {
                type: Array,
                required: true
            },

            initIndex: {
                type: Number,
                default: 0
            }
        },

        data() {
            const {initIndex} = this;
            return {
                visible: false,
                index: initIndex,
                isSwitching: false
            };
        },

        computed: {
            currentImage() {
                const {imageList, index} = this;

                if (index < 0) return {};
                return imageList[index];
            },

            canGoPrev() {
                const {index} = this;

                return index > 0;
            },

            canGoNext() {
                const {index, imageList} = this;

                const flag = index < imageList.length - 1;

                return flag;
            },

            keyMap() {
                const {goPrev, goNext, cancel} = this;
                return {
                    left: goPrev,
                    right: goNext,
                    esc: cancel
                };
            }
        },

        methods: {
            cancel() {
                const vm = this;
                vm.reject();
            },

            confirm() {
                const vm = this;
                vm.resolve();
            },

            goPrev() {
                const vm = this;
                const {canGoPrev} = vm;

                if (!canGoPrev) return;

                vm.index -= 1;
                vm.isSwitching = true;
                vm.$nextTick(() => {
                    vm.isSwitching = false;
                });
            },

            goNext() {
                const vm = this;
                const {canGoNext} = vm;

                if (!canGoNext) return;

                vm.index += 1;
                vm.isSwitching = true;
                vm.$nextTick(() => {
                    vm.isSwitching = false;
                });
            }
        }
    };

</script>
