<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-10-15 18:29:12.941 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>

    <div class="b-nav-top">
        <div class="nav-wrap container-wide">
            <div class="nav container-wide mat">
                <div class="nav-menu container">
                    <div class="nav-drop">
                        <div class="icon-toggle" @click="toggleDropDownMenu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div class="nav-left" @click="closeDropDownMenu">
                        <slot name="left"></slot>
                    </div>

                    <div class="nav-root-wrap level-center">
                        <ul class="level-center">
                            <li
                                v-for="route in navRoutes"
                                :key="route.path">
                                <router-link
                                    :to="route"
                                    :class="{'active': activeRootRoute.name === route.name}"
                                    class="nav-link">
                                    {{ route.meta.navTitle }}
                                </router-link>
                            </li>
                        </ul>
                    </div>

                    <div class="nav-center">
                        <slot name="center"></slot>
                    </div>

                    <div class="nav-right">
                        <slot name="right"></slot>
                    </div>
                </div>

                <transition name="nav-slide">
                    <div
                        v-b-click-outside="closeDropDownMenu"
                        v-if="isDropDownMenuOpen"
                        class="nav-drop-menu container-wide">
                        <ul class="container b-col">
                            <li
                                v-for="route in navRoutes"
                                :key="route.name"
                                :class="{'active': activeRootRoute.name === route.name}">
                                <div class="drop-menu-item" @click="dropMenuJump(route)">{{ route.meta.navTitle }}</div>
                            </li>
                        </ul>
                    </div>
                </transition>
            </div>

            <div v-if="subRoutes.length" class="sub-nav container-wide level-center">
                <ul class="level-center sub-nav-list">
                    <li
                        v-for="route in subRoutes"
                        :key="route.name"
                        :class="{'active': activeSubRoute.name === route.name}"
                        class="sub-nav-item">
                        <router-link :to="route">{{ route.meta.navTitle }}</router-link>
                    </li>
                </ul>
            </div>
        </div>

        <div class="nav-buffer"></div>
        <div v-if="subRoutes.length" class="sub-nav-buffer"></div>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BNavTop',

        props: {
            routes: {
                type: Array,
                required: true
            }
        },

        data() {
            const vm = this;
            const {routes, genNavRoutes} = vm;

            return {
                navRoutes: genNavRoutes(routes),
                isDropDownMenuOpen: false
            };
        },

        computed: {
            activeRootRoute() {
                const {navRoutes, $route: {name: curName}} = this;

                const RootActiveRoute = navRoutes.find(({name}) => name === curName);
                const RootSubActiveRoute = navRoutes.find(
                    (rootRoot = {children: []}) => rootRoot.children.some((route = {}) => route.name === curName)
                );
                return RootActiveRoute || RootSubActiveRoute || {};
            },

            activeSubRoute() {
                const {subRoutes, $route: {name: curName}} = this;

                return subRoutes.find(({name}) => name === curName) || {};
            },

            subRoutes() {
                const vm = this;
                const {activeRootRoute} = vm;

                if (!activeRootRoute) return [];

                return activeRootRoute.children || [];
            }
        },

        mounted() {
            const vm = this;
            vm.$watch('routes', () => {
                vm.refreshNavRoutes();
            });
        },

        methods: {
            isActive({name, path}) {
                const vm = this;
                const {$route} = vm;

                if ($route.name === name) return true;

                return $route.path.indexOf(path) !== -1;
            },

            isRouteRender(route) {
                const {meta = {}} = route;

                return meta.navTitle;
            },

            toggleDropDownMenu() {
                const vm = this;

                vm.isDropDownMenuOpen = !vm.isDropDownMenuOpen;
            },

            closeDropDownMenu() {
                const vm = this;

                vm.isDropDownMenuOpen = false;
            },

            dropMenuJump(route) {
                const vm = this;

                vm.$router.replace(route);
                vm.isDropDownMenuOpen = false;
            },

            refreshNavRoutes() {
                const vm = this;
                const {routes, genNavRoutes} = vm;

                vm.navRoutes = genNavRoutes(routes);
            },

            genNavRoutes(routes) {
                const vm = this;

                const rootRoutes = routes.filter(({meta}) => (meta && meta.navTitle));

                rootRoutes.forEach((rootRoute) => {
                    const defaultRootOpen = rootRoute.meta.defaultOpen;
                    vm.$set(rootRoute, '$$open', defaultRootOpen !== undefined ? defaultRootOpen : true);

                    const secondRoutes = rootRoute.children || [];
                    rootRoute.children = secondRoutes.filter(({meta}) => (meta && meta.navTitle));
                });

                return rootRoutes;
            }
        }
    };

</script>

