<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-10-16 15:04:05.869 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>

    <div class="comp-image-gallery">
        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">图片墙</span>
                    <code>b-image-gallery</code>
                </h2>
                <b-md-view :md-text="MD.CompImageGalleryOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompImageGalleryBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompImageGalleryBasicCode"/></div>
                    <div slot="main">
                        <b-image-gallery :image-list="imageList"/>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompImageGalleryAPI"/>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    export default {
        name: 'CompImageGallery',

        data() {
            return {
                MD,
                imageList: [
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3f021xij21hc0u0b29.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3eyikq6j20g00a0q3g.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3f380luj24yd20kqva.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3eyits8j20dw09qmxy.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3ezmol1j218a0q9b1y.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3f1b3mdj218g0p0b2a.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3f00ck4j20zk0k07qs.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3f1fyukj21z4140b2a.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3ezzci0j215o0tjtsa.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3ezx5vej20k00rs1d8.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3eyqr8mj218g0p013b.jpg'},
                    {uri: 'https://ws1.sinaimg.cn/large/a51018d9ly1fwa3ez1u4cj20xc0j0167.jpg'}
                ]
            };
        }
    };

</script>
