<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-21 13:03:25.630 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div class="comp-date-string">
        <h4 class="heading">Date String</h4>

        <div class="card">
            <form class="form-inline" @submit.prevent>
                <b-form-group label="Basic">
                    <b-date-string v-model="editing.basic"/>
                </b-form-group>

                <b-form-group label="With Default Value">
                    <b-date-string v-model="editing.default"/>
                </b-form-group>

                <b-form-group label="Disabled">
                    <b-date-string v-model="editing.disabled" :disabled="true"/>
                </b-form-group>
            </form>
        </div>

        <pre class="json-preview">{{ $j(editing) }}</pre>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'CompDate',

        data() {
            return {
                editing: {
                    basic: null,
                    default: '2018-04-01',
                    disabled: '1993-09-17'
                }
            };
        }
    };

</script>
