<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-28 00:11:38.310 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="comp-date">

        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">日期选择器</span>
                    <code>b-date</code>
                </h2>
                <b-md-view :md-text="MD.CompDateOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompDateBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompDateBasicCode"/></div>
                    <div slot="main">
                        <b-date v-model="demo.basic"/>
                    </div>
                    <div slot="output">The output is {{ demo.basic }}</div>
                </demo-box>
            </div>

            <div class="case">
                <h3>Round 模式</h3>
                <b-md-view :md-text="MD.CompDateRound"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompDateRoundCode"/></div>
                    <div slot="main">
                        <b-form-group label="Dat Start (Default)">
                            <b-date v-model="demo.dayStart"/>
                        </b-form-group>

                        <b-form-group label="Day End">
                            <b-date v-model="demo.dayEnd" :day-end="true"/>
                        </b-form-group>
                    </div>
                    <div slot="output">
                        Day Start Mode: {{ demo.dayStart }} <br>
                        Day End Mode: {{ demo.dayEnd }}
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>Format</h3>
                <b-md-view :md-text="MD.CompDateFormat"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompDateFormatCode"/></div>
                    <div slot="main">
                        <b-form-group label="Function Format">
                            <b-date v-model="demo.formatFunction" :format="getDate"/>
                        </b-form-group>

                        <b-form-group label="String Format">
                            <b-date v-model="demo.formatString" format="ISO"/>
                        </b-form-group>
                    </div>
                    <div slot="output">
                        Function Format: {{ demo.formatFunction }} <br>
                        String Format: {{ demo.formatString }}
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>一致性</h3>
                <b-md-view :md-text="MD.CompDateConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompDateAPI"/>
            </div>
        </div>

    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    const getDate = timestamp => (new Date(timestamp)).toJSON().slice(0, 10);

    export default {
        name: 'CompDate',

        data() {
            return {
                MD,
                getDate,

                demo: {
                    basic: null,
                    dayStart: null,
                    dayEnd: null,
                    formatFunction: null,
                    formatString: null
                }
            };
        }
    };

</script>

