<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-28 01:00:41.514 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="plugin-alert">

        <h4 class="heading">Alert</h4>
        <div class="card">
            <button @click="alert">Alert</button>
        </div>

    </div>

</template>

<script type="text/babel">

    export default {
        name: 'PluginAlert',

        methods: {
            alert() {
                const vm = this;
                vm.$alert.success('Dialog Content', 'Title');
            }
        }
    };

</script>

