<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-28 13:03:29.047 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <div v-if="visible" :class="{'in-dialog': isInBDialog}" class="b-popper-wrap">
        <div ref="popper" :name="name" class="b-popper">
            <slot></slot>
        </div>
    </div>

</template>

<script type="text/babel">

    import BDialog from '../b-dialog';
    import {getWindowRect, getRect} from '../../util/dom';
    import {isValidPlacement} from './helper/helper';

    export default {
        name: 'BPopper',

        props: {
            name: {
                type: String,
                default: null
            },

            visible: {
                type: Boolean,
                default: false
            },

            placement: {
                type: String,
                validator: isValidPlacement,
                default: 'bottom-start'
            }
        },

        computed: {
            isInBDialog() {
                const vm = this;

                let isInDialog = false;
                const rec = ({$parent}) => {
                    if (!$parent) return;

                    if ($parent.$options.name === BDialog.name) {
                        isInDialog = true;
                        return;
                    }

                    rec($parent);
                };

                rec(vm);

                return isInDialog;
            }
        },

        updated() {
            const vm = this;
            const {$el, $refs: {popper}, visible} = vm;

            if (visible) {
                vm.$nextTick(() => vm.makePosition($el.parentNode, popper));
            }
        },

        methods: {
            makePosition(ref, el) {
                const vm = this;
                const {placement} = vm;

                const refRect = getRect(ref);
                const elRect = getRect(el);
                const windowRect = getWindowRect();

                let x = 0, y = refRect.bottom - elRect.top; // eslint-disable-line

                if ((elRect.right > windowRect.innerWidth && (windowRect.innerWidth - refRect.right) > elRect.width)
                    || (elRect.left < refRect.left)) {
                    x = -(elRect.width - refRect.width);
                }

                const TotalHeight = refRect.height + elRect.height;
                const DiffWidth = refRect.width - elRect.width;

                switch (placement) {
                    case 'top-start': {
                        Object.assign(el.style, {
                            left: `${x}px`,
                            top: `${y - TotalHeight}px`
                        });
                        break;
                    }
                    case 'top': {
                        Object.assign(el.style, {
                            left: `${x + DiffWidth / 2}px`,
                            top: `${y - TotalHeight}px`
                        });
                        break;
                    }
                    case 'top-end': {
                        Object.assign(el.style, {
                            left: `${x + DiffWidth}px`,
                            top: `${y - TotalHeight}px`
                        });
                        break;
                    }
                    case 'right-start': {
                        Object.assign(el.style, {
                            left: `${x + refRect.width}px`,
                            top: `${y - refRect.height}px`
                        });
                        break;
                    }
                    case 'right': {
                        Object.assign(el.style, {
                            left: `${x + refRect.width}px`,
                            top: `${y - TotalHeight / 2}px`
                        });
                        break;
                    }
                    case 'right-end': {
                        Object.assign(el.style, {
                            left: `${x + refRect.width}px`,
                            top: `${y - elRect.height}px`
                        });
                        break;
                    }
                    case 'bottom-start': {
                        Object.assign(el.style, {
                            left: `${x}px`,
                            top: `${y}px`
                        });
                        break;
                    }
                    case 'bottom': {
                        Object.assign(el.style, {
                            left: `${x + DiffWidth / 2}px`,
                            top: `${y}px`
                        });
                        break;
                    }
                    case 'bottom-end': {
                        Object.assign(el.style, {
                            left: `${x + DiffWidth}px`,
                            top: `${y}px`
                        });
                        break;
                    }
                    case 'left-start': {
                        Object.assign(el.style, {
                            left: `${x - elRect.width}px`,
                            top: `${y - refRect.height}px`
                        });
                        break;
                    }
                    case 'left': {
                        Object.assign(el.style, {
                            left: `${x - elRect.width}px`,
                            top: `${y - TotalHeight / 2}px`
                        });
                        break;
                    }
                    case 'left-end': {
                        Object.assign(el.style, {
                            left: `${x - elRect.width}px`,
                            top: `${y - elRect.height}px`
                        });
                        break;
                    }
                    default: {
                        Object.assign(el.style, {left: `${x}px`, top: `${y}px`});
                        break;
                    }
                }
            }
        }
    };

</script>
