<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-28 13:03:29.047 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <div v-if="visible" :class="{'in-dialog': isInBDialog}" class="b-popper-wrap">
        <div ref="popper" class="b-popper">
            <slot></slot>
        </div>
    </div>

</template>

<script type="text/babel">

    import BDialog from '../b-dialog';
    import {getWindowRect, getRect} from '../../util/dom';

    export default {
        name: 'BPopper',

        props: {
            visible: {
                type: Boolean,
                default: false
            }
        },

        computed: {
            isInBDialog() {
                const vm = this;

                let isInDialog = false;
                const rec = ({$parent}) => {
                    if (!$parent) return;

                    if ($parent.$options.name === BDialog.name) {
                        isInDialog = true;
                        return;
                    }

                    rec($parent);
                };

                rec(vm);

                return isInDialog;
            }
        },

        updated() {
            const vm = this;
            const {$el, $refs: {popper}, visible} = vm;

            if (visible) {
                vm.$nextTick(() => vm.makePosition($el.parentNode, popper));
            }
        },

        methods: {
            makePosition(ref, el) {
                const refRect = getRect(ref);
                const elRect = getRect(el);
                const windowRect = getWindowRect();

                let x = 0, y = 0; // eslint-disable-line
                if ((elRect.right > windowRect.innerWidth && (windowRect.innerWidth - refRect.right) > elRect.width)
                    || (elRect.left < refRect.left)) {
                    x = -(elRect.width - refRect.width);
                }

                if ((elRect.bottom > windowRect.innerHeight && refRect.top > refRect.height)
                    || (elRect.bottom < refRect.bottom)) {
                    y = -(elRect.height + refRect.height);
                }

                Object.assign(el.style, {left: `${x}px`, top: `${y}px`});
            }
        }
    };

</script>
