<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-26 15:18:12.050 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="comp-popper">

        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">悬浮卡片</span>
                    <code>b-popper</code>
                </h2>
                <b-md-view :md-text="MD.CompPopperOverview"/>
            </div>

            <div class="case">
                <h3>可点击</h3>
                <b-md-view :md-text="MD.CompPopperBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompPopperBasicCode"/></div>
                    <div slot="main" class="main">
                        <div class="demo-detail">
                            <div v-b-click-outside="() => {closePopper(1)}" class="popper-group">
                                <b-button @click="openPopper(1)">Open Popper</b-button>
                                <b-popper :visible="isPopperVisible1">
                                    <div class="action-card">
                                        这是一个 Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>方位</h3>
                <b-md-view :md-text="MD.CompPopperPlacement"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompPopperPlacementCode"/></div>
                    <div slot="main">
                        <div class="demo-detail top-row">
                            <div v-b-click-outside="() => {closePopper(2)}" class="popper-group">
                                <b-button @click="openPopper(2)">Top Start</b-button>
                                <b-popper :visible="isPopperVisible2" placement="top-start">
                                    <div class="action-card">
                                        Top Start Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(3)}" class="popper-group">
                                <b-button @click="openPopper(3)">Top</b-button>
                                <b-popper :visible="isPopperVisible3" placement="top">
                                    <div class="action-card">
                                        Top Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(4)}" class="popper-group">
                                <b-button @click="openPopper(4)">Top End</b-button>
                                <b-popper :visible="isPopperVisible4" placement="top-end">
                                    <div class="action-card">
                                        Top End Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                        <div class="demo-detail mid-row">
                            <div v-b-click-outside="() => {closePopper(5)}" class="popper-group">
                                <b-button @click="openPopper(5)">Left Start</b-button>
                                <b-popper :visible="isPopperVisible5" placement="left-start">
                                    <div class="action-card">
                                        Left Start Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(6)}" class="popper-group">
                                <b-button @click="openPopper(6)">Right Start</b-button>
                                <b-popper :visible="isPopperVisible6" placement="right-start">
                                    <div class="action-card">
                                        Right Start Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                        <div class="demo-detail mid-row">
                            <div v-b-click-outside="() => {closePopper(7)}" class="popper-group">
                                <b-button @click="openPopper(7)">Left</b-button>
                                <b-popper :visible="isPopperVisible7" placement="left">
                                    <div class="action-card">
                                        Left Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(8)}" class="popper-group">
                                <b-button @click="openPopper(8)">Right</b-button>
                                <b-popper :visible="isPopperVisible8" placement="right">
                                    <div class="action-card">
                                        Right Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                        <div class="demo-detail mid-row">
                            <div v-b-click-outside="() => {closePopper(9)}" class="popper-group">
                                <b-button @click="openPopper(9)">Left End</b-button>
                                <b-popper :visible="isPopperVisible9" placement="left-end">
                                    <div class="action-card">
                                        Left End Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(10)}" class="popper-group">
                                <b-button @click="openPopper(10)">Right End</b-button>
                                <b-popper :visible="isPopperVisible10" placement="right-end">
                                    <div class="action-card">
                                        Right End Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                        <div class="demo-detail top-row">
                            <div v-b-click-outside="() => {closePopper(11)}" class="popper-group">
                                <b-button @click="openPopper(11)">Bottom Start</b-button>
                                <b-popper :visible="isPopperVisible11" placement="bottom-start">
                                    <div class="action-card">
                                        Bottom Start Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(12)}" class="popper-group">
                                <b-button @click="openPopper(12)">Bottom</b-button>
                                <b-popper :visible="isPopperVisible12" placement="bottom">
                                    <div class="action-card">
                                        Bottom Popper
                                    </div>
                                </b-popper>
                            </div>
                            <div v-b-click-outside="() => {closePopper(13)}" class="popper-group">
                                <b-button @click="openPopper(13)">Bottom End</b-button>
                                <b-popper :visible="isPopperVisible13" placement="bottom-end">
                                    <div class="action-card">
                                        Bottom End Popper
                                    </div>
                                </b-popper>
                            </div>
                        </div>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>表单一致性</h3>
                <b-md-view :md-text="MD.CompPopperConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompPopperAPI"/>
            </div>
        </div>

    </div>

</template>

<script type="text/babel">
    import MD from '../../../common/md';

    export default {
        name: 'CompPopper',

        data() {
            return {
                MD,
                isPopperVisible1: false,
                isPopperVisible2: false,
                isPopperVisible3: false,
                isPopperVisible4: false,
                isPopperVisible5: false,
                isPopperVisible6: false,
                isPopperVisible7: false,
                isPopperVisible8: false,
                isPopperVisible9: false,
                isPopperVisible10: false,
                isPopperVisible11: false,
                isPopperVisible12: false,
                isPopperVisible13: false
            };
        },

        methods: {
            closePopper(keyIndex) {
                const key = `isPopperVisible${keyIndex}`;
                this[key] = false;
            },

            openPopper(keyIndex) {
                const key = `isPopperVisible${keyIndex}`;
                this[key] = true;
            }
        }
    };

</script>

<style lang="scss" scoped>
    @import "../../../../../src/style/variables.scss";

    .comp-popper {
        .demo-detail {
            text-align: center;

            &.top-row {
                display: flex;
                justify-content: center;

                @media screen and (max-width: $tablet-min) {
                    display: block;
                }
            }

            &.mid-row {
                display: flex;
                justify-content: space-around;

                @media screen and (max-width: $tablet-min) {
                    display: block;
                }
            }

            .popper-group {
                display: inline-block;
                margin: 10px 20px;

                .action-card {
                    width: 180px;
                    padding: 20px;
                    font-size: 18px;
                    text-align: center;
                }

                @media screen and (max-width: $tablet-min) {
                    display: block;
                }
            }
        }
    }
</style>
