<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-25 11:12:12.421 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="comp-card">

        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">卡片</span>
                    <code>b-card</code>
                </h2>
                <b-md-view :md-text="MD.CompCardOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompCardBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompCardBasicCode"/></div>
                    <div slot="main">
                        <b-card>
                            <b-card-header title="孔乙己" sub-title="鲁迅">
                                <div slot="header-action">
                                    <div v-b-click-outside="closePopper">
                                        <b-button shape="icon" @click="openPopper">
                                            <i class="b-icon-more"></i>
                                        </b-button>
                                        <b-popper :visible="isPopperVisible">
                                            <div class="action-card" style="width: 200px; margin-left: -170px;">
                                                <div class="action-group">
                                                    <button class="action-bar">
                                                        编辑 <i class="b-icon-edit"></i>
                                                    </button>
                                                    <button class="action-bar">
                                                        删除 <i class="b-icon-trash"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </b-popper>
                                    </div>
                                </div>
                            </b-card-header>
                            <b-card-body>{{ sample }}</b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>附带图片</h3>
                <b-md-view :md-text="MD.CompCardMedia"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompCardMediaCode"/></div>
                    <div slot="main">
                        <b-card>
                            <b-card-header title="Card Title" sub-title="Sub Title"/>
                            <b-card-body>
                                <b-card-media title="数码宝贝" sub-title="八神太一">
                                    <img src="./constant/img/childhood.jpg">
                                </b-card-media>
                            </b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>可点击</h3>
                <b-md-view :md-text="MD.CompCardClickable"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompCardClickableCode"/></div>
                    <div slot="main">
                        <b-card clickable @click="handleClick">
                            <b-card-header title="Card Title" sub-title="Sub Title"/>
                            <b-card-body>
                                <b-card-media title="数码宝贝" sub-title="八神太一">
                                    <img src="./constant/img/childhood.jpg">
                                </b-card-media>
                            </b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>宽度</h3>
                <b-md-view :md-text="MD.CompCardSize"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompCardSizeCode"/></div>
                    <div slot="main">
                        <b-card size="sm">
                            <b-card-header title="孔乙己" sub-title="鲁迅"/>
                            <b-card-body>{{ sample }}</b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                    <div slot="main">
                        <b-card>
                            <b-card-header title="孔乙己" sub-title="鲁迅"/>
                            <b-card-body>{{ sample }}</b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                    <div slot="main">
                        <b-card size="lg">
                            <b-card-header title="孔乙己" sub-title="鲁迅"/>
                            <b-card-body>{{ sample }}</b-card-body>
                            <b-card-footer>
                                <b-button shape="icon">
                                    <i class="b-icon-love"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-share"></i>
                                </b-button>
                                <b-button shape="icon">
                                    <i class="b-icon-info"></i>
                                </b-button>
                            </b-card-footer>
                        </b-card>
                    </div>
                </demo-box>
            </div>

            <div class="case">
                <h3>表单一致性</h3>
                <b-md-view :md-text="MD.CompCardConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompCardAPI"/>
            </div>

        </div>
    </div>

</template>

<script type="text/babel">
    import MD from '../../../common/md';

    export default {
        name: 'CompCard',

        data() {
            return {
                MD,
                isPopperVisible: false,
                sample: `孔乙己睁大眼睛说，“你怎么这样凭空污人清白……”“什么清白？我前天亲眼见
                        你偷了何家的书，吊着打。”孔乙己便涨红了脸，额上的青筋条条绽出，争辩道，
                        “窃书不能算偷……窃书！……读书人的事，能算偷么？”接连便是难懂的话，
                        什么“君子固穷”，什么“者乎”之类，引得众人都哄笑起来。`
            };
        },

        methods: {
            closePopper() {
                this.isPopperVisible = false;
            },

            openPopper() {
                this.isPopperVisible = true;
            },

            handleClick() {
                const vm = this;
                vm.$toast.info('卡片被点击');
            }
        }
    };

</script>
