<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-07-03 15:47:19.191 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="b-select-cascader">
        <div
            v-b-click-outside="closeMenu"
            :class="{'disabled': disabled, 'b-resettable': canBeReset}"
            class="b-select">
            <b-input
                ref="input"
                :name="name"
                :value="searchText"
                :disabled="disabled"
                :placeholder="placeholder"
                type="text"
                @focus="openMenu">
                <i
                    slot="right"
                    :class="{'b-select-icon-active': menuOpen}"
                    class="b-right-icon b-icon-arrow-bottom"
                    @click="reset"></i>
            </b-input>

            <b-popper :visible="menuOpen">
                <b-select-cascader-menu
                    :list="list"
                    :value="selectedList"
                    :search-text="searchText"
                    :enable-emit-list="options.enableEmitList"
                    @choose="choose"/>
            </b-popper>
        </div>
    </div>

</template>

<script type="text/babel">

    import {
        getSelectedListFromSingleValue,
        getSelectedListFromListValue
    } from './helper/helper';
    import BSelectCascaderMenu from './b-select-cascader-menu.vue';

    export default {
        name: 'BSelectCascader',

        components: {BSelectCascaderMenu},

        model: {
            prop: 'value',
            event: 'change'
        },

        props: {
            value: {
                type: null,
                required: true
            },
            list: {
                type: Array,
                required: true
            },
            options: {
                type: Object,
                default: () => ({})
            },
            name: {
                type: String,
                default: ''
            },
            placeholder: {
                type: String,
                default: '请选择'
            },
            disabled: {
                type: Boolean,
                default: false
            },
            enableReset: {
                type: Boolean,
                default: true
            }
        },

        data() {
            return {
                menuOpen: false,
                selectedList: []
            };
        },

        computed: {
            canBeReset() {
                const {enableReset, searchText} = this;
                return enableReset && !!searchText;
            },

            searchText() {
                const {selectedList} = this;

                return selectedList.map(({label}) => label).join('/');
            }
        },

        mounted() {
            const {options: {enableEmitList = false}, value, list} = this;
            const selectedList = enableEmitList
                ? getSelectedListFromListValue(list, value)
                : getSelectedListFromSingleValue(list, value);

            this.selectedList = selectedList;
        },

        methods: {
            openMenu() {
                this.menuOpen = true;
            },

            closeMenu() {
                this.menuOpen = false;
            },

            reset() {
                this.$emit('change', null);
                this.selectedList = [];
            },

            choose(selectedList) {
                const vm = this;
                const {options: {
                    enableEmitList = false
                }} = vm;

                const leafItem = selectedList[selectedList.length - 1];
                if (!leafItem.children || !leafItem.children.length) {
                    vm.closeMenu(); // if is leaf item, close menu
                }

                if (enableEmitList) {
                    vm.$emit('change', selectedList.map(({value}) => (value)));
                    vm.selectedList = selectedList;
                    return;
                }

                // when enableEmitList is false, emit change only if is leaf item
                if (!leafItem.children || !leafItem.children.length) {
                    vm.$emit('change', leafItem.value);
                    vm.selectedList = selectedList;
                }
            }
        }
    };

</script>

