<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-02-28 19:36:19.260 -->
<!-- @desc generated by yqg-cli@0.0.16 -->

<template>

    <div class="conceptions container">
        <div class="card">
            <b-md-view :md-text="MD.IntroConceptions"/>
        </div>
    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    export default {
        name: 'Conceptions',

        data() {
            return {
                MD
            };
        }
    };

</script>

<style lang="scss" rel="stylesheet/scss" scoped></style>
