<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-29 21:12:30.752 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="b-layout">
        <slot name="header"></slot>

        <div>
            <div @click="onNavClick">
                <slot name="side-left"></slot>
            </div>

            <div :class="{'menu-opened': isNavOpen}" class="content">
                <slot name="content"></slot>
            </div>
            <slot name="side-right"></slot>
        </div>

        <slot name="footer"></slot>

        <div v-if="isNavOpen" class="nav-mask lg-hide sm-show" @click="onNavClick"></div>
    </div>

</template>

<script type="text/babel">

    import {isMobile} from '../../util/dom';

    export default {
        name: 'BLayout',

        props: {
            defaultOpen: {
                type: Boolean,
                default: true
            },

            isNavOpen: {
                type: Boolean,
                default: true
            }
        },

        mounted() {
            const vm = this;
            const {defaultOpen} = vm;
            vm.$emit('nav-open-change', !isMobile() && defaultOpen);
        },

        methods: {
            onNavClick() {
                const vm = this;
                if (isMobile()) {
                    vm.$emit('nav-open-change', false);
                }
            }
        }
    };

</script>
