<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-30 15:26:09.925 -->
<!-- @desc generated by yqg-cli@0.1.12 -->

<template>

    <div class="b-nav-side">
        <nav class="nav">
            <div class="action-card">
                <div class="action-group">
                    <div class="nav-header">
                        <slot name="toggle">
                            <div class="icon-toggle" @click="onToggle">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </slot>

                        <slot name="nav-top"></slot>
                    </div>
                </div>

                <div v-if="navRoutes">
                    <div v-for="rootRoute in navRoutes" :key="rootRoute.name" class="action-group nav-wrap">
                        <!-- has children -->
                        <button
                            v-if="rootRoute.children.length"
                            class="action-bar router-level-1"
                            @click="onToggleNavChildrenOpen(rootRoute)"
                        >
                            <span v-if="rootRoute.meta.hasIcon">
                                <slot :name="rootRoute.name">
                                    <i :class="rootRoute.meta.iconClass"></i>
                                </slot>
                            </span>
                            {{ rootRoute.meta.navTitle }}

                            <span class="toggle-icon">
                                <i v-if="rootRoute.$$open" class="b-icon-bottom"></i>
                                <i v-else class="b-icon-right"></i>
                            </span>
                        </button>

                        <!-- no child -->
                        <router-link
                            v-else
                            :to="{name: rootRoute.name}"
                            :class="{active: rootRoute.name === $route.name}"
                            class="action-bar router-level-1"
                        >
                            <span v-if="rootRoute.meta.hasIcon">
                                <slot :name="rootRoute.name">
                                    <i :class="rootRoute.meta.iconClass"></i>
                                </slot>
                            </span>
                            {{ rootRoute.meta.navTitle }}
                        </router-link>

                        <!-- children -->
                        <div v-if="rootRoute.$$open">
                            <div
                                v-for="secondRoute in rootRoute.children"
                                :key="secondRoute.name"
                            >
                                <router-link
                                    :to="{name: secondRoute.name}"
                                    :class="{active: secondRoute.name === $route.name}"
                                    class="action-bar router-level-2">
                                    {{ secondRoute.meta.navTitle }}
                                </router-link>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BNavSide',

        props: {
            routes: {
                type: Array,
                required: true
            }
        },

        data() {
            const vm = this;
            const {routes, genNavRoutes} = vm;

            return {
                navRoutes: genNavRoutes(routes)
            };
        },

        mounted() {
            const vm = this;
            vm.$watch('routes', () => {
                vm.refreshNavRoutes();
            });
        },

        methods: {
            onToggle() {
                this.$emit('toggle');
            },

            onToggleNavChildrenOpen(route) {
                route.$$open = !route.$$open;
            },

            refreshNavRoutes() {
                const vm = this;
                const {routes, genNavRoutes} = vm;

                vm.navRoutes = genNavRoutes(routes);
            },

            genNavRoutes(routes) {
                const vm = this;

                const rootRoutes = routes.filter(({meta}) => (meta && meta.navTitle));

                rootRoutes.forEach((rootRoute) => {
                    const defaultRootOpen = rootRoute.meta.defaultOpen;
                    vm.$set(rootRoute, '$$open', defaultRootOpen !== undefined ? defaultRootOpen : true);

                    const secondRoutes = rootRoute.children || [];
                    rootRoute.children = secondRoutes.filter(({meta}) => (meta && meta.navTitle));
                });

                return rootRoutes;
            }
        }
    };

</script>
