<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-30 15:26:09.925 -->
<!-- @desc generated by yqg-cli@0.1.12 -->

<template>

    <div class="b-nav-side">
        <nav class="nav">
            <div class="action-card">
                <div class="action-group">
                    <div class="nav-header">
                        <slot name="toggle">
                            <div class="icon-toggle" @click="onToggle">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </slot>

                        <slot name="nav-top"></slot>
                    </div>
                </div>

                <div v-for="rootRoute in navRoutes" :key="rootRoute.name" class="action-group nav-wrap">
                    <div class="action-header">
                        <router-link :to="{name: rootRoute.name}">
                            {{ rootRoute.meta.navTitle }}
                        </router-link>
                    </div>

                    <router-link
                        v-for="secondRoute in rootRoute.children"
                        :key="secondRoute.name"
                        :to="{name: secondRoute.name}"
                        :class="{active: secondRoute.name === $route.name}"
                        class="action-bar">
                        {{ secondRoute.meta.navTitle }}
                        <i class="b-icon-arrow-right"></i>
                    </router-link>
                </div>
            </div>
        </nav>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BNavSide',

        props: {
            routes: {
                type: Array,
                required: true
            }
        },

        computed: {
            navRoutes() {
                const vm = this;
                const {routes} = vm;

                const navRoutes = routes.filter(({meta}) => (meta && meta.navTitle));
                navRoutes.forEach((rootRoute) => {
                    const secondRoutes = rootRoute.children;
                    rootRoute.children = secondRoutes.filter(({meta}) => (meta && meta.navTitle));
                });

                return navRoutes;
            }
        },

        methods: {
            onToggle() {
                this.$emit('toggle');
            }
        }
    };

</script>
