<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-20 22:19:07.992 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="b-header">
        <div class="header-buffer"></div>

        <header class="header">
            <div class="left">
                <slot name="toggle">
                    <div class="icon-toggle" @click="toggleNav">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </slot>

                <slot name="logo"></slot>
            </div>

            <div class="center">
                <slot name="center"></slot>
            </div>

            <div class="right">
                <slot name="right"></slot>
            </div>
        </header>
    </div>

</template>

<script type="text/babel">
export default {
  name: 'BHeader',

  methods: {
    toggleNav() {
      this.$emit('on-nav-toggle');
    }
  }
};
</script>

