<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'YqgWebDiffLintEngine' => 'lint/engine/YqgWebDiffLintEngine.php',
    'YqgWebLintEngine' => 'lint/engine/YqgWebLintEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'YqgWebDiffLintEngine' => 'ArcanistLintEngine',
    'YqgWebLintEngine' => 'ArcanistLintEngine',
  ),
));
