<!-- @author Rain -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-06-29 11:12:07.835 -->
<!-- @desc generated by yqg-cli@0.2.0 -->

<template>
    <div class="component">
        <h4 class="heading">Markdown Editor</h4>

        <div class="card">
            <div class="comp-md-editor">
                <b-md-editor
                    v-model="mdText"
                    :options="options"
                    :customized-style="customizedStyle"/>
            </div>
        </div>

        <pre class="json-preview">{{ $j(mdText) }}</pre>
    </div>

</template>

<script type="text/babel">

    import mdSampleText from './sample.md';

    const options = {
        actionList: [
            {
                name: 'image',

                icon: 'b-icon-image',

                insert: (selectionText) => {
                    const imgUrl = 'http://ww1.sinaimg.cn/mw690/005ODVHQly1fsxwxh2607j30o10ecq4n.jpg';
                    return selectionText ? `![${selectionText}](${imgUrl})` : `![description](${imgUrl})`;
                }
            }
        ]
    };

    export default {
        name: 'CompMdEditor',

        data() {
            return {
                options,
                mdText: mdSampleText,
                customizedStyle: {
                    height: '552px'
                }
            };
        }
    };

</script>
