<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-25 11:32:49.747 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="b-card-body">
        <slot></slot>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BCardBody'
    };

</script>
