<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-28 00:59:32.475 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="plugin">
        <div class="container">
            <transition name="slide-fade" mode="out-in">
                <router-view class="view"/>
            </transition>
        </div>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'Plugin'
    };

</script>

