<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-10 16:35:54.623 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div class="comp-image">
        <h4 class="heading">Image</h4>

        <div class="card">
            <form class="form-inline" @submit.prevent>
                <b-form-group label="Basic">
                    <b-image v-model="editing.basic"/>
                </b-form-group>

                <b-form-group label="Basic">
                    <b-image v-model="editing.crop"/>
                </b-form-group>
            </form>
        </div>

        <pre class="json-preview">{{ $j(editingData) }}</pre>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'CompImage',

        data() {
            return {
                editing: {
                    basic: null,
                    crop: null
                }
            };
        },

        computed: {
            editingData() {
                const {editing} = this;

                return Object.keys(editing).reduce((acc, cur) => {
                    const file = editing[cur];

                    if (!file) {
                        acc[cur] = null;
                        return acc;
                    }

                    const {type, name, size, lastModified} = file;
                    acc[cur] = {
                        type,
                        name,
                        size,
                        lastModified
                    };

                    return acc;
                }, {});
            }
        }
    };

</script>
