<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-10 16:35:54.623 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div class="comp-image">
        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">图片选择器</span>
                    <code>b-image</code>
                </h2>
                <b-md-view :md-text="MD.CompImageOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompImageBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompImageBasicCode"/></div>
                    <div slot="main">
                        <b-image v-model="demo.basic"/>
                    </div>
                    <div slot="output">The output is {{ genInfo(demo.basic) }}</div>
                </demo-box>
            </div>

            <div class="case">
                <h3>一致性</h3>
                <b-md-view :md-text="MD.CompImageConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompImageAPI"/>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import MD from '../../../common/md';

    export default {
        name: 'CompImage',

        data() {
            return {
                MD,
                demo: {
                    basic: null
                }
            };
        },

        methods: {
            genInfo(file) {
                if (!file) return null;

                const {type, name, size, lastModified} = file;
                return {
                    type,
                    name,
                    size,
                    lastModified
                };
            }
        }

    };

</script>
