<!-- @author yanglan -->
<!-- @email yanglan@yangqianguan.com -->
<!-- @date 2018-04-16 17:12:07.835 -->
<!-- @desc generated by yqg-cli@0.1.0-beta.8 -->

<template>

    <div class="comp-form">
        <h4 class="heading">Form</h4>

        <div class="card">
            <b-form v-model="data" :options="options">
                <b-form-group slot="custom" label="自定义 field">
                    <b-input v-model="data.custom"/>
                </b-form-group>
            </b-form>
        </div>

        <pre class="json-preview">{{ $j(data) }}</pre>
    </div>

</template>

<script type="text/babel">
    const options = {
        fieldDefs: [
            {label: '名称', field: 'name'},
            {field: 'custom'},
            {label: '科目', field: 'type', type: 'select', props: {map: {a: 'a', b: 'b'}}},
            {label: '时间', field: 'time', type: 'date'}
        ]
    };

    export default {
        name: 'CompForm',

        data() {
            return {
                options,

                data: {
                    name: '123',
                    custom: '',
                    type: ''
                }
            };
        }
    };

</script>
