<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-08-09 16:29:37.108 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div
        class="b-date-time">
        <div class="date">
            <b-date
                v-model="date"
                :disabled="disabled"
                @change="handleChooseTime"/>
        </div>

        <div class="time division">
            <b-select
                v-model="hour"
                :map="HoursMap"
                :enable-reset="false"
                :disabled="disableTime"
                placeholder="HH"
                @tab="handleHourTab"
                @change="handleChooseTime"/>
        </div>

        <div class="time division">
            <b-select
                v-model="minute"
                :map="MinutesMap"
                :enable-reset="false"
                :disabled="disableTime"
                placeholder="mm"
                @tab="handleMinuteTab"
                @change="handleChooseTime"/>
        </div>

        <div class="time">
            <b-select
                v-model="second"
                :map="SecondsMap"
                :disabled="disableTime"
                placeholder="ss"
                @tab="handleSecondTab"
                @change="handleChooseTime"/>
            <i
                v-if="enabledReset"
                :class="{'b-date-time-icon-active': !disableTime}"
                class="b-right-icon b-icon-arrow-bottom"
                @click="reset"></i>
        </div>
    </div>

</template>

<script type="text/babel">
    import {getTimeDigitalComponent} from '../../util/time';

    import BDatePicker from '../b-date/b-date-picker.vue';
    import BInput from '../b-input';

    import {genMap, paddingSearchText} from './helper/helper';

    export default {
        name: 'BDateTime',

        components: {
            BInput,
            BDatePicker
        },

        model: {
            prop: 'value',
            event: 'change'
        },

        props: {
            value: {
                type: [Number, String],
                validator: value => isFinite(new Date(value)),
                default: null
            },

            disabled: {
                type: Boolean,
                default: false
            },

            enabledReset: {
                type: Boolean,
                default: true
            }
        },

        data() {
            return {
                HoursMap: genMap(24),
                MinutesMap: genMap(60),
                SecondsMap: genMap(60),
                date: null,
                hour: null,
                minute: null,
                second: null
            };
        },

        computed: {
            disableTime() {
                return this.date === null;
            }
        },

        methods: {
            handleHourTab(searchText) {
                this.handleTab(searchText, 'hour', this.HoursMap);
            },

            handleMinuteTab(searchText) {
                this.handleTab(searchText, 'minute', this.MinutesMap);
            },

            handleSecondTab(searchText) {
                this.handleTab(searchText, 'second', this.SecondsMap);
            },

            handleTab(value, field, map) {
                const vm = this;
                const normalizdValue = paddingSearchText(value);
                if (map[normalizdValue] === undefined) return;
                vm[field] = normalizdValue;
                vm.handleChooseTime();
            },

            handleChooseTime() {
                const vm = this;
                if (vm.hour === null && vm.minute === null && vm.second === null) {
                    vm.hour = '0';
                    vm.minute = '0';
                    vm.second = '0';
                }
                const {hour, minute, second} = vm;
                const {year, month, date} = getTimeDigitalComponent(vm.date);

                vm.$emit('change', new Date(year, month - 1, date, hour, minute, second).getTime());
            },

            reset() {
                const vm = this;
                if (vm.value === null) return;
                vm.hour = null;
                vm.minute = null;
                vm.second = null;
                vm.date = null;

                vm.$emit('change', null);
            }
        }
    };

</script>
