<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-08-09 16:29:37.108 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div
        class="b-date-time">
        <div class="date">
            <b-date
                :value="timeComponents.dateStartTime"
                :disabled="disabled"
                @change="handleDateChange"/>
        </div>

        <div class="time division">
            <b-select
                :value="timeComponents.hour"
                :map="HoursMap"
                :enable-reset="false"
                :disabled="disableTime"
                placeholder="HH"
                @tab="handleHourChange"
                @change="handleHourChange"/>
        </div>

        <div class="time division">
            <b-select
                :value="timeComponents.minute"
                :map="MinutesMap"
                :enable-reset="false"
                :disabled="disableTime"
                placeholder="mm"
                @tab="handleMinuteChange"
                @change="handleMinuteChange"/>
        </div>

        <div class="time">
            <b-select
                :value="timeComponents.second"
                :map="SecondsMap"
                :disabled="disableTime"
                placeholder="ss"
                @tab="handleSecondChange"
                @change="handleSecondChange"/>
            <i
                v-if="enabledReset"
                :class="{'b-date-time-icon-active': !disableTime}"
                class="b-right-icon b-icon-arrow-bottom"
                @click="reset"></i>
        </div>
    </div>

</template>

<script type="text/babel">
    import {getTimeDigitalComponent} from '../../util/time';

    import BDatePicker from '../b-date/b-date-picker.vue';
    import BInput from '../b-input';

    import {genMap, paddingSearchText} from './helper/helper';

    export default {
        name: 'BDateTime',

        components: {
            BInput,
            BDatePicker
        },

        model: {
            prop: 'value',
            event: 'change'
        },

        props: {
            value: {
                type: [Number, String],
                validator: value => isFinite(new Date(value)),
                default: null
            },

            disabled: {
                type: Boolean,
                default: false
            },

            enabledReset: {
                type: Boolean,
                default: true
            }
        },

        data() {
            return {
                HoursMap: genMap(24),
                MinutesMap: genMap(60),
                SecondsMap: genMap(60)
            };
        },

        computed: {
            disableTime() {
                return this.timeComponents.dateStartTime === null;
            },

            timeComponents() {
                const {value} = this;
                if (!value) {
                    return {
                        dateStartTime: null,
                        hour: null,
                        minute: null,
                        second: null
                    };
                }

                const {year, month, date, hour, minute, second} = getTimeDigitalComponent(value);
                const dateStartTime = new Date(year, month - 1, date).getTime();

                return {
                    dateStartTime,
                    hour,
                    minute,
                    second
                };
            }
        },

        methods: {
            handleDateChange(dateStartTime) {
                this.handleChooseTime(dateStartTime, 'dateStartTime');
            },

            handleHourChange(searchText) {
                this.handleChooseTime(searchText, 'hour', this.HoursMap);
            },

            handleMinuteChange(searchText) {
                this.handleChooseTime(searchText, 'minute', this.MinutesMap);
            },

            handleSecondChange(searchText) {
                this.handleChooseTime(searchText, 'second', this.SecondsMap);
            },

            handleChooseTime(value, field, map) {
                const vm = this;
                const normalizdValue = paddingSearchText(value);
                if (map && map[normalizdValue] === undefined) return;

                const {dateStartTime, hour, minute, second} = {
                    ...vm.timeComponents,
                    [field]: value
                };
                const {year, month, date} = getTimeDigitalComponent(dateStartTime);

                vm.$emit('change', new Date(year, month - 1, date, hour, minute, second).getTime());
            },

            reset() {
                this.$emit('change', null);
            }
        }
    };

</script>
