<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-07-26 13:21:50.686 -->
<!-- @desc generated by yqg-cli@0.2.4 -->

<template>

    <div class="comp-tab">
        <h4 class="heading">Tab</h4>

        <div class="card">
            <div class="card">
                <b-tab :list="TabList" :default-index="1" class="tab-inset" @tap="tap"/>
                Active Key: {{ key }}
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    const TabList = [
        {label: 'Web', key: 'web'},
        {label: 'Images', key: 'image'},
        {label: 'Videos', key: 'vedio'},
        {label: 'Academic', key: 'academic'},
        {label: 'Dict', key: 'dict'},
        {label: 'Maps', key: 'map'}
    ];

    export default {
        name: 'CompTab',

        data() {
            return {
                TabList,
                key: 'image'
            };
        },

        methods: {
            tap({key}) {
                this.key = key;
            }
        }
    };

</script>

