<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-28 01:00:53.389 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="plugin-modal">
        <h4 class="heading">Modal</h4>
        <div class="card">
            <button @click="messageModal">Message Modal</button>
            <button @click="modal">Customized Modal</button>
        </div>
    </div>

</template>

<script type="text/babel">

    import TestGulpModal from './modal/test-gulp-modal';

    export default {
        name: 'PluginModal',

        methods: {
            modal() {
                const vm = this;

                vm.$modal
                    .open(TestGulpModal)
                    .then((resolve) => {
                        vm.$toast.info(resolve);
                    })
                    .catch(x => x);
            },

            messageModal() {
                const vm = this;

                vm.$modal
                    .openMessageModal('You are reading the message', 'Notice')
                    .then(() => vm.$toast.success('You confirmed!'))
                    .catch(() => vm.$toast.info('You canceled!'));
            }
        }
    };

</script>

