<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-10 16:26:23.967 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div :class="{'b-resettable': canBeReset}" class="b-image">
        <b-input
            :value="imageName"
            :name="name"
            :placeholder="placeholder"
            :disabled="disabled"
            type="text">
            <i
                slot="right"
                class="b-right-icon b-icon-image"
                @click="reset"></i>
        </b-input>

        <input
            :multiple="multiple"
            :value="valueToSelect"
            type="file"
            accept="image/x-png,image/gif,image/jpeg"
            @change="onSelect">

        <div class="image-preview-wrap">
            <div v-if="previewImages.length" class="image-preview-list">
                <div v-for="(image, index) in previewImages" :key="index" class="image-preview">
                    <img :src="image.uri">
                    <div class="mask" @click="checkImage(image)">
                        <i class="b-icon-search"></i>
                        <i class="b-icon-trash" @click.stop="remove(index)"></i>
                    </div>
                </div>

                <b-button v-if="multiple" class="create" shape="icon">
                    <input
                        :multiple="multiple"
                        :value="valueToAdd"
                        type="file"
                        style="width:100%;"
                        accept="image/x-png,image/gif,image/jpeg"
                        @change="onAdd">
                    <i class="b-icon-create"></i>
                </b-button>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import {getBase64} from '../../util/image';
    import BInput from '../b-input';
    import BImageCheckModal from './b-image-check-modal';

    const OUTSIDE = 'OUTSIDE';
    const INSIDE = 'INSIDE';

    export default {
        name: 'BImage',

        components: {
            BInput
        },

        model: {
            value: 'value',
            event: 'change'
        },

        props: {
            name: {
                type: String,
                default: ''
            },

            disabled: {
                type: Boolean,
                default: false
            },

            placeholder: {
                type: String,
                default: '请选择'
            },

            multiple: {
                type: Boolean,
                default: false
            },

            previewMode: {
                type: String,
                validator: val => [OUTSIDE, INSIDE].indexOf(val) !== -1,
                default: INSIDE
            },

            previewList: {
                type: Array,
                default: () => ([])
            },

            enableReset: {
                type: Boolean,
                default: true
            },

            checkSize: {
                type: String,
                default: ''
            }
        },

        data() {
            return {
                OUTSIDE,
                INSIDE,

                images: [],
                files: [],
                valueToSelect: null,
                valueToAdd: null
            };
        },

        computed: {
            canBeReset() {
                const vm = this;
                const {previewImages, disabled, enableReset} = vm;

                return previewImages.length && enableReset && !disabled;
            },

            imageName() {
                const vm = this;
                const {previewImages} = vm;
                if (!previewImages.length) return '';

                if (previewImages.length === 1 && previewImages[0].name) {
                    return previewImages[0].name;
                }

                if (previewImages.length === 1) {
                    return '1 image';
                }

                return `${previewImages.length} images`;
            },

            previewImages() {
                const vm = this;
                const {images, previewList, previewMode} = vm;

                return previewMode === INSIDE ? images : previewList;
            }
        },

        methods: {
            onSelect(event) {
                const vm = this;
                const {multiple} = this;

                if (multiple) {
                    vm.onAdd(event);
                    return;
                }

                vm.onChange(event);
            },

            async onChange(event) {
                const vm = this;
                const {multiple} = vm;
                const oriFiles = event.target.files || event.dataTransfer.files;

                if (!oriFiles.length) return;
                vm.files = Array.from(oriFiles);
                vm.images = [];

                await Promise.all(vm.files.map(async (file) => {
                    vm.images.push({
                        name: file.name,
                        uri: await getBase64(file),
                        file
                    });
                }));

                if (!multiple) {
                    vm.$emit('change', vm.files[0]);
                    return;
                }

                vm.$emit('change', vm.files);
                vm.valueToSelect = null;
            },

            async onAdd(event) {
                const vm = this;
                const {previewMode} = vm;
                const oriFiles = event.target.files || event.dataTransfer.files;

                if (!oriFiles.length) return;

                const newFiles = Array.from(oriFiles);

                if (previewMode === INSIDE) {
                    await Promise.all(newFiles.map(async (file) => {
                        vm.images.push({
                            name: file.name,
                            uri: await getBase64(file),
                            file
                        });
                    }));

                    vm.$emit('change', vm.files.concat(newFiles));
                }

                vm.$emit('add', newFiles);
                vm.valueToAdd = null;
            },

            reset() {
                const vm = this;
                const {previewMode} = vm;
                vm.images = [];

                if (previewMode === OUTSIDE) {
                    vm.$emit('reset');
                    return;
                }

                vm.$emit('change', null);
            },

            checkImage(image) {
                const vm = this;
                const {checkSize} = vm;
                vm.$modal.open(BImageCheckModal, {image, checkSize}).catch(x => x);
            },

            remove(index) {
                const vm = this;
                const {previewMode, multiple} = vm;

                if (previewMode === INSIDE) {
                    vm.images.splice(index, 1);
                    vm.files.splice(index, 1);

                    if (!multiple) {
                        vm.$emit('change', null);
                        return;
                    }

                    vm.$emit('change', vm.files);
                }

                vm.$emit('remove', index);
            }
        }
    };

</script>
