<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-05-10 16:26:23.967 -->
<!-- @desc generated by yqg-cli@0.1.8 -->

<template>

    <div :class="{'b-resettable': canBeReset}" class="b-image">
        <b-input
            :value="image.name"
            :name="name"
            :placeholder="placeholder"
            :disabled="disabled"
            type="text">
            <i
                slot="right"
                class="b-right-icon b-icon-image"
                @click="reset"></i>
        </b-input>

        <input
            type="file"
            accept="image/x-png,image/gif,image/jpeg"
            @change="onChange">

        <div class="image-preview-wrap">
            <div v-if="image.base64" class="image-preview">
                <img :src="image.base64">
                <div class="mask" @click="checkImage">
                    <i class="b-icon-search"></i>
                </div>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import {getBase64} from '../../util/image';
    import BInput from '../b-input';
    import BImageCheckModal from './b-image-check-modal';

    export default {
        name: 'BImage',

        components: {
            BInput
        },

        model: {
            value: 'value',
            event: 'change'
        },

        props: {
            name: {
                type: String,
                default: ''
            },

            disabled: {
                type: Boolean,
                default: false
            },

            placeholder: {
                type: String,
                default: '请选择'
            },

            enableReset: {
                type: Boolean,
                default: true
            },

            checkSize: {
                type: String,
                default: ''
            }
        },

        data() {
            return {
                image: {
                    name: '',
                    base64: ''
                }
            };
        },

        computed: {
            canBeReset() {
                const vm = this;
                const {image: {name}, disabled, enableReset} = vm;

                return name && enableReset && !disabled;
            }
        },

        methods: {
            async onChange(event) {
                const vm = this;
                const files = event.target.files || event.dataTransfer.files;

                if (!files.length) return;

                const file = files[0];
                vm.image = {
                    name: file.name,
                    base64: await getBase64(file),
                    file
                };

                vm.$emit('change', file);
            },

            reset() {
                const vm = this;
                vm.image = {
                    name: '',
                    base64: ''
                };
                vm.$emit('change', null);
            },

            checkImage() {
                const vm = this;
                const {image, checkSize} = vm;
                vm.$modal.open(BImageCheckModal, {image, checkSize}).catch(x => x);
            }
        }
    };

</script>
