<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-10-16 14:19:10.243 -->
<!-- @desc generated by yqg-cli@0.3.6 -->

<template>

    <div class="b-image-gallery">
        <div class="image-preview-list">
            <div v-for="(image, index) in imageList" :key="index" class="image-preview">
                <img :src="image.uri">
                <div class="mask" @click="checkImage(index)">
                    <i class="b-icon-search"></i>
                </div>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">

    import BImageGalleryModal from './b-image-gallery-modal';

    export default {
        name: 'BImageGallery',

        props: {
            imageList: {
                type: Array,
                required: true
            }
        },

        methods: {
            checkImage(index) {
                const vm = this;
                const {imageList} = vm;
                vm.$modal.open(BImageGalleryModal, {imageList, initIndex: index}).catch(x => x);
            }
        }
    };

</script>

