<!-- @author Kyles Light -->
<!-- @email likelakes07@gmail.com -->
<!-- @date 2018-07-28 01:00:29.406 -->
<!-- @desc generated by yqg-cli@0.1.13 -->

<template>

    <div class="plugin-toast">
        <h4 class="heading">Toast</h4>
        <div class="card">
            <button @click="toastError">Error</button>
            <button @click="toastSuccess">Success</button>
            <button @click="toastInfo">Info</button>
        </div>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'PluginToast',

        methods: {
            toastInfo() {
                const vm = this;
                vm.$toast.info('Please stand firm and hold the handrail.');
            },

            toastSuccess() {
                const vm = this;
                vm.$toast.success('Success!');
            },

            toastError() {
                const vm = this;
                vm.$toast.error('You shall not pass');
            }
        }
    };

</script>

