<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-25 11:32:20.088 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="b-card-header">
        <div class="b-card-header-title">
            <div class="b-card-title">{{ title }}</div>
            <div class="b-card-subtitle">{{ subTitle }}</div>
        </div>

        <div class="b-card-header-action">
            <slot name="header-action"></slot>
        </div>

        <slot></slot>

    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BCardHeader',

        props: {
            title: {
                type: String,
                default: ''
            },
            subTitle: {
                type: String,
                default: ''
            }
        }
    };

</script>
