<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-06-29 16:51:02.867 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="b-md-editor">
        <div class="app-bar">
            <button
                v-for="action in ActionList"
                :key="action.name"
                class="simple"
                @click="callAction(action)">
                <i :class="'b-icon-' + (action.description || 'adjust')"></i>
            </button>
        </div>

        <div :style="customizedStyle" class="container-content">
            <textarea
                ref="textarea"
                :value="value"
                class="textarea"
                @input="onInput"></textarea>

            <b-md-view :md-text="value" class="md-view"/>
        </div>
    </div>

</template>

<script type="text/babel">
    import {ActionList} from '../../constant/ActionConf';

    export default {
        name: 'BMdEditor',

        model: {
            prop: 'value',
            event: 'change'
        },

        props: {
            value: {
                type: String,
                required: true
            },
            options: {
                type: Object,
                default: () => {}
            },
            customizedStyle: {
                type: Object,
                default: () => {}
            }
        },

        data() {
            return {
                actionMap: {
                    onHeader: this.onHeader,
                    onBold: this.onBold,
                    onItalic: this.onItalic,
                    onLink: this.onLink,
                    onQuote: this.onQuote,
                    onCode: this.onCode
                },
                actionPreMap: {
                    onBold: {
                        preLeftPattern: '** ',
                        preRightPattern: ' **',
                        patternLength: 3,
                        addPattern: '** bold text **',
                        addPatternLength: 15
                    },
                    onItalic: {
                        preLeftPattern: '_ ',
                        preRightPattern: ' _',
                        patternLength: 2,
                        addPattern: '_ italic text _',
                        addPatternLength: 15
                    }
                }
            };
        },

        computed: {
            ActionList() {
                const {options} = this;
                return options && options.actionList ? options.actionList : ActionList;
            }
        },

        methods: {
            callAction(action) {
                if (action.method) {
                    const {$refs: {textarea, textarea: {value: originText}}} = this;
                    const {mdText, leftSelectionChange, rightSelectionChange} = action.method(originText, textarea);
                    this.emitChange(mdText);
                    this.postHandleCursor(3, leftSelectionChange, rightSelectionChange);
                } else {
                    this.actionMap[action.methodName]();
                }

            },

            preHandleBlock(leftPattern, rightPattern, patternLength, addPattern) {
                const {$refs: {textarea, textarea: {selectionStart, selectionEnd, value: originText}}} = this;
                const preResult = {newText: '', cursorCase: 0};
                if ('selectionStart' in textarea) {
                    if (selectionStart !== selectionEnd) {
                        if (originText.substring(selectionStart - patternLength, selectionStart) === leftPattern
                            && originText.substring(selectionEnd, selectionEnd + patternLength) === rightPattern) {
                            preResult.newText = `${originText.substring(0, selectionStart - patternLength)
                                }${originText.substring(selectionStart, selectionEnd)
                                }${originText.substring(selectionEnd + patternLength)}`;
                            preResult.cursorCase = 1;
                        } else {
                            preResult.newText = `${originText.substring(0, selectionStart)
                                }${leftPattern}${originText.substring(selectionStart, selectionEnd)
                                }${rightPattern}${originText.substring(selectionEnd)}`;
                            preResult.cursorCase = 0;
                        }
                    } else {
                        preResult.newText = `${originText.substring(0, selectionStart)
                             }${addPattern}${originText.substring(selectionEnd)}`;
                        preResult.cursorCase = 2;
                    }
                }
                return preResult;
            },

            postHandleCursor(cursorCase, patternLength, addPatternLength) {
                const {textarea, textarea: {selectionStart, selectionEnd}} = this.$refs;
                setTimeout(() => {
                    if (cursorCase === 0) {
                        textarea.setSelectionRange(selectionStart + patternLength,
                            selectionEnd + patternLength);
                    } else if (cursorCase === 1) {
                        textarea.setSelectionRange(selectionStart - patternLength,
                            selectionEnd - patternLength);
                    } else if (cursorCase === 2) {
                        textarea.setSelectionRange(selectionStart + patternLength,
                            selectionEnd + (addPatternLength - patternLength));
                    } else {
                        textarea.setSelectionRange(selectionStart + patternLength,
                            selectionEnd + addPatternLength);
                    }
                    textarea.focus();
                }, 1);
            },

            onHeader() {
                const {$refs: {textarea, textarea: {selectionStart, value: originText}}} = this;
                if ('selectionStart' in textarea) {
                    let newText = '';
                    let selectionChange = 0;
                    const topLineIndex = originText.lastIndexOf('\n', selectionStart - 1) + 1;
                    if (originText.charAt(topLineIndex) !== '#'
                        && originText.charAt(topLineIndex) !== ' ') {
                        newText = `${originText.substring(0, topLineIndex)
                            }# ${originText.substring(topLineIndex)}`;
                        selectionChange = 2;
                    } else {
                        newText = `${originText.substring(0, topLineIndex)
                        }#${originText.substring(topLineIndex)}`;
                        selectionChange = 1;
                    }
                    this.emitChange(newText);
                    this.postHandleCursor(3, selectionChange, selectionChange);
                }
            },

            onBold() {
                const {
                    preLeftPattern,
                    preRightPattern,
                    patternLength,
                    addPattern,
                    addPatternLength
                } = this.actionPreMap.onBold;
                const result = this.preHandleBlock(preLeftPattern,
                    preRightPattern,
                    patternLength,
                    addPattern);
                this.emitChange(result.newText);
                this.postHandleCursor(result.cursorCase,
                    patternLength,
                    addPatternLength);
            },

            onItalic() {
                const {
                    preLeftPattern,
                    preRightPattern,
                    patternLength,
                    addPattern,
                    addPatternLength
                } = this.actionPreMap.onItalic;
                const result = this.preHandleBlock(preLeftPattern,
                    preRightPattern,
                    patternLength,
                    addPattern);
                this.emitChange(result.newText);
                this.postHandleCursor(result.cursorCase,
                    patternLength,
                    addPatternLength);
            },

            onLink() {
                const {$refs: {textarea, textarea: {selectionStart, selectionEnd, value: originText}}} = this;
                if ('selectionStart' in textarea) {
                    let newText = '';
                    let leftSelectionChange = 0;
                    let rightSelectionChange = 0;
                    if (selectionStart !== selectionEnd) {
                        newText = `${originText.substring(0, selectionStart)
                             }[${originText.substring(selectionStart, selectionEnd)
                             }](link_url)${originText.substring(selectionEnd)}`;
                        leftSelectionChange = (selectionEnd - selectionStart) + 3;
                        rightSelectionChange = 11;
                    } else {
                        newText = `${originText.substring(0, selectionStart)
                             }[link_text](link_url)${originText.substring(selectionEnd)}`;
                        leftSelectionChange = 12;
                        rightSelectionChange = 20;
                    }
                    this.emitChange(newText);
                    this.postHandleCursor(3, leftSelectionChange, rightSelectionChange);
                }
            },

            onQuote() {
                const {$refs: {textarea, textarea: {selectionStart, value: originText}}} = this;
                if ('selectionStart' in textarea) {
                    let newText = '';
                    let selectionChange;
                    const topLineIndex = originText.lastIndexOf('\n', selectionStart - 1) + 1;
                    if (originText.charAt(topLineIndex) !== '>'
                        && originText.charAt(topLineIndex) !== ' ') {
                        newText = `${originText.substring(0, topLineIndex)
                            }> ${originText.substring(topLineIndex)}`;
                        selectionChange = 2;
                    } else {
                        newText = `${originText.substring(0, topLineIndex)
                        }${originText.substring(topLineIndex + 2)}`;
                        selectionChange = -2;
                    }
                    this.emitChange(newText);
                    this.postHandleCursor(3, selectionChange, selectionChange);
                }
            },

            onCode() {
                const {$refs: {textarea, textarea: {selectionStart, selectionEnd, value: originText}}} = this;
                let newText = '';
                let leftSelectionChange = 0;
                let rightSelectionChange = 0;
                const cursorCase = 3;
                if ('selectionStart' in textarea) {
                    if (selectionStart !== selectionEnd) {
                        // 选到行首
                        if (originText.charAt(selectionStart - 1) === '\n' || selectionStart === 0) {
                            if (originText.substring(selectionStart - 4, selectionStart) === '```\n'
                                && originText.substring(selectionEnd, selectionEnd + 4) === '\n```') {
                                newText = `${originText.substring(0, selectionStart - 4)
                                    }${originText.substring(selectionStart, selectionEnd)
                                    }${originText.substring(selectionEnd + 4)}`;
                                leftSelectionChange = -4;
                                rightSelectionChange = -4;
                            } else {
                                newText = `${originText.substring(0, selectionStart)
                                    }\`\`\`\n${originText.substring(selectionStart, selectionEnd)
                                    }\n\`\`\`${originText.substring(selectionEnd)}`;
                                leftSelectionChange = 4;
                                rightSelectionChange = 4;
                            }
                        } else if (originText.substring(selectionStart - 1, selectionStart) === '`'
                                && originText.substring(selectionEnd, selectionEnd + 1) === '`') {
                                newText = `${originText.substring(0, selectionStart - 1)
                                    }${originText.substring(selectionStart, selectionEnd)
                                    }${originText.substring(selectionEnd + 1)}`;
                                leftSelectionChange = -1;
                                rightSelectionChange = -1;
                            } else {
                                newText = `${originText.substring(0, selectionStart)
                                    }\`${originText.substring(selectionStart, selectionEnd)
                                    }\`${originText.substring(selectionEnd)}`;
                                leftSelectionChange = 1;
                                rightSelectionChange = 1;
                            }
                    } else {
                        newText = `${originText.substring(0, selectionStart)
                             }\n\`\`\`\ncode block\n\`\`\`\n${originText.substring(selectionEnd)}`;
                        leftSelectionChange = 5;
                        rightSelectionChange = 15;
                    }
                }
                this.emitChange(newText);
                this.postHandleCursor(cursorCase, leftSelectionChange, rightSelectionChange);
            },

            onInput() {
                const {$refs: {textarea: {value}}} = this;
                this.emitChange(value);
            },

            emitChange(value) {
                this.$emit('change', value);
            }
        }
    };

</script>
