<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-06-29 16:51:02.867 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="b-md-editor">
        <div class="app-bar">
            <button
                v-for="action in actionList"
                :key="action.name"
                class="simple"
                @click="callAction(action)">
                <i :class="action.icon"></i>
            </button>
        </div>

        <div :style="customizedStyle" class="container-content">
            <textarea
                ref="textarea"
                :value="value"
                class="textarea"
                @input="onInput"></textarea>

            <b-md-view :md-text="value" class="md-view"/>
        </div>
    </div>

</template>

<script type="text/babel">

    import bold from './action/bold';
    import code from './action/code';
    import header from './action/header';
    import italic from './action/italic';
    import link from './action/link';
    import quote from './action/quote';

    const DEFAULT_ACTION_LIST = [
        header,
        bold,
        italic,
        link,
        quote,
        code
    ];

    const DEFAULT_OPTIONS = {
        override: false,
        actionList: [], // 用户定义的 action list
        actionOrder: null // 定义 action 展示的顺序，用 name 指定
    };

    export default {
        name: 'BMdEditor',

        model: {
            prop: 'value',
            event: 'change'
        },

        props: {
            value: {
                type: String,
                required: true
            },

            options: {
                type: Object,
                default: () => ({})
            },

            customizedStyle: {
                type: Object,
                default: () => ({})
            }
        },

        computed: {
            actionList() {
                const options = Object.assign({}, DEFAULT_OPTIONS, this.options);
                const {override, actionList: optionActionList, actionOrder} = options;
                const actionList = override ? optionActionList : [...DEFAULT_ACTION_LIST, ...optionActionList];

                if (actionOrder) {
                    const actionMap = actionList.reduce((map, cur) => {
                        map[cur.name] = cur; // 用 name 作为 key
                        return map;
                    }, {});

                    return actionOrder.map(name => actionMap[name]);
                }

                return actionList;
            }
        },

        created() {
            Object.defineProperties(this, { // could not use computed, so use this for convenient
                textarea: {
                    get() {
                        return this.$refs && this.$refs.textarea;
                    }
                },

                text: {
                    get() {
                        return this.textarea && this.textarea.value;
                    }
                },

                selectionStart: {
                    get() {
                        return this.textarea && this.textarea.selectionStart;
                    }
                },

                selectionEnd: {
                    get() {
                        return this.textarea && this.textarea.selectionEnd;
                    }
                },

                selectionText: {
                    get() {
                        const {textarea, selectionStart, selectionEnd, text} = this;
                        if (!textarea) return '';
                        return (selectionStart === selectionEnd) ? '' : text.slice(selectionStart, selectionEnd);
                    }
                }
            });
        },

        methods: {
            callAction(action = {}) {
                if (action.insert) {
                    return this.handleInsert(action);
                }

                if (action.modify) {
                    return this.handleModify(action);
                }

                return null;
            },

            async handleInsert(action) {
                const {textarea, text, selectionText, selectionStart, selectionEnd} = this;
                const replaceText = await action.insert(selectionText);
                const newText = `${text.slice(0, selectionStart)}${replaceText}${text.slice(selectionEnd)}`;
                this.emitChange(newText);
                this.$nextTick(() => {
                    textarea.setSelectionRange(selectionStart, selectionStart + replaceText.length);
                    textarea.focus();
                });
            },

            async handleModify(action) {
                const {textarea, text, selectionStart, selectionEnd} = this;
                const {
                    text: newText,
                    selectionStart: newSelectionStart,
                    selectionEnd: newSelectionEnd
                } = await action.modify({text, selectionStart, selectionEnd});
                this.emitChange(newText);
                this.$nextTick(() => {
                    textarea.setSelectionRange(newSelectionStart, newSelectionEnd);
                    textarea.focus();
                });
            },

            onInput() {
                const {$refs: {textarea: {value}}} = this;
                this.emitChange(value);
            },

            emitChange(value) {
                this.$emit('change', value);
            }
        }
    };

</script>
