<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-08-09 16:34:05.960 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div class="comp-date-time">

        <div class="doc card">
            <div class="overview">
                <h2>
                    <span class="title">日期时间选择器</span>
                    <code>b-date-time</code>
                </h2>
                <b-md-view :md-text="MD.CompDateTimeOverview"/>
            </div>

            <div class="case">
                <h3>基本用法</h3>
                <b-md-view :md-text="MD.CompDateTimeBasic"/>

                <demo-box>
                    <div slot="code"><b-md-view :md-text="MD.CompDateTimeBasicCode"/></div>
                    <div slot="main">
                        <b-date-time v-model="demo.basic"/>
                    </div>
                    <div slot="output">The output is {{ demo.basic }}</div>
                </demo-box>
            </div>

            <div class="case">
                <h3>一致性</h3>
                <b-md-view :md-text="MD.CompDateTimeConsistent"/>
            </div>

            <div class="case">
                <h3>API</h3>
                <b-md-view :md-text="MD.CompDateTimeAPI"/>
            </div>
        </div>
    </div>

</template>

<script type="text/babel">
    import MD from '../../../common/md';

    export default {
        name: 'CompDateTime',

        data() {
            return {
                MD,
                demo: {
                    basic: null
                }
            };
        }
    };

</script>
