<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-02-28 19:30:21.116 -->
<!-- @desc generated by yqg-cli@0.0.16 -->

<template>

    <div class="intro">
        <router-view class="view"/>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'Intro'
    };

</script>

<style lang="scss" rel="stylesheet/scss" scoped></style>
