<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-02-28 19:30:21.116 -->
<!-- @desc generated by yqg-cli@0.0.16 -->

<template>

    <div class="intro">
        <transition name="slide-fade" mode="out-in">
            <router-view class="view"/>
        </transition>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'Intro'
    };

</script>

