<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-07-26 13:08:08.298 -->
<!-- @desc generated by yqg-cli@0.2.4 -->

<template>

    <div class="b-tab">
        <ul class="b-tab-wrap">
            <li
                v-for="(item, index) in list"
                :key="item.key"
                :class="{active: index === activeIndex}"
                class="b-tab-item"
                @click="tap(item, index)">
                <slot :active="index === activeIndex" :item="item">
                    {{ item.label }}
                </slot>
            </li>
        </ul>
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'BTab',

        props: {
            list: {
                type: Array,
                required: true
            },

            defaultIndex: {
                type: Number,
                default: 0
            }
        },

        data() {
            return {
                activeIndex: 0
            };
        },

        mounted() {
            const vm = this;
            const {defaultIndex} = vm;

            if (defaultIndex > -1) {
                vm.activeIndex = defaultIndex;
            }
        },

        methods: {
            tap(item, index) {
                const vm = this;
                vm.activeIndex = index;
                vm.$emit('tap', item, index);
            }
        }
    };

</script>

