<!-- @author yutiangan -->
<!-- @email yutiangan@yangqianguan.com -->
<!-- @date 2018-09-17 16:02:47.034 -->
<!-- @desc generated by yqg-cli@0.2.2 -->

<template>

    <div :class="className" class="b-button">
        <button
            :autofocus="autofocus"
            :disabled="disabled"
            :name="name"
            :style="btnStyle"
            :type="type"
            @click="handleClick">
            <slot></slot>
        </button>
    </div>

</template>

<script type="text/babel">
    import {isValidType, isValidShape, isValidSize} from './helper/helper';

    export default {
        name: 'BButton',

        props: {
            autofocus: {
                type: Boolean,
                default: false
            },

            btnStyle: {
                type: Object,
                default: () => {}
            },

            disabled: {
                type: Boolean,
                default: false
            },

            name: {
                type: String,
                default: null
            },

            shape: {
                type: String,
                validator: isValidShape,
                default: null
            },

            size: {
                type: String,
                validator: isValidSize,
                default: null
            },

            type: {
                type: String,
                validator: isValidType,
                default: null
            }
        },

        computed: {
            className() {
                const vm = this;
                const {shape, size} = vm;

                return [
                    ...(shape ? [shape] : []),
                    ...(size ? [size] : [])
                ];
            }
        },

        methods: {
            handleClick(event) {
                const vm = this;
                vm.$emit('click', event);
            }
        }
    };

</script>
